export async function statusHandler(sock) {
    sock.ev.on('messages.upsert', async ({ messages }) => {
        const m = messages[0]

        if (!m?.key?.remoteJid) return

        // Only handle actual WhatsApp statuses
        if (m.key.remoteJid !== 'status@broadcast') return

        // Ignore messages generated by our own bot
        if (m.key.fromMe) return

        // Ignore status reactions
        if (m.message?.reactionMessage) return

        try {
            // Auto view status
            await sock.readMessages([m.key])

            // Optional auto react
            const emojis = ['❤️', '🔥', '😍', '👏']
            const randomEmoji =
                emojis[Math.floor(Math.random() * emojis.length)]

            await sock.sendMessage('status@broadcast', {
                react: {
                    text: randomEmoji,
                    key: m.key
                }
            }).catch(() => {})

            console.log(
                `✅ Viewed status from ${m.key.participant || 'unknown'}`
            )
        } catch (error) {
            console.error('❌ Status handler error:', error.message)
        }
    })
}
